### ISSUE TITLE
Settings vs constrainable properties

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-depth#102]
The way Media Capture and Streams currently operates, the set of constrainable properties is the same as the set of settings obtained via getSettings().

This spec uses settings to report on non-constrainable properties.

That might be OK, but since that's clearly something that hasn't been done before, it would be good to check that this is consistent with the rest of the contrainable model.

**Comment by jan-ivar** [comment]
We have at least one existing read-only constrainable property: `facingMode`, yet we still populate `MediaTrackCapabilities` and `MediaTrackConstraints` with `facingMode`.

**Comment by anssiko** [comment]
Any further suggestions what, if any, changes we should do to the mediacapture-depth spec to be consistent with this model defined in the mediacapture-main?

**Comment by jan-ivar** [comment]
Mirroring what we do for `facingMode` should make it consistent. Sites can then choose or reject a camera through `getUserMedia` based on these properties (should users ever find themselves with more than one depth camera).

**Comment by anssiko** [comment]
I looked at how mediacapture-main defines `facingMode` but I did not see any reusable concise wording, thus I minted a new "non-constrainable property" definition and applied it to `focalLength`, `horizontalFieldOfView`, and `verticalFieldOfView`

Any concerns? Please review the PR #119.

**Comment by anssiko** [comment]
Closed with PR #119.

Since there was some iteration in the PR, for historical reference, see https://github.com/w3c/mediacapture-depth/pull/119/commits
