### ISSUE TITLE
Quantization formulas aren't accessible

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-depth#105]
Images are used for the "rules to convert using range linear" and "rules to convert using range inverse", but their alt attributes just says "Quantization", with no accessible description of the formulas.

**Comment by anssiko** [comment]
Fixed with a0caf75 using the ASCIIMath notation.

**Comment by anssiko** [comment]
Improve this further in 9cad17c.

**Comment by dontcallmedom** [comment]
re mathjax, you might want to chime in in the respec discussion on how to include 3rd party scripts in respec based documents (now and in the future) https://github.com/w3c/respec/pull/678

**Comment by marcoscaceres** [comment]
@anssiko please see https://github.com/WebAudio/web-audio-api/pull/782
