### ISSUE TITLE
focalLength, *fieldOfView scope

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-depth#106]
Right now, focalLength and horizontal/verticalFieldOfView are described as specific to depth sources; presumably they would be useful for other video sources as well.

**Comment by anssiko** [comment]
There's now the following note in the [Constrainable properties](http://w3c.github.io/mediacapture-depth/#constrainable-properties) section:

> The `focalLength`, `horizontalFieldOfView`, and `verticalFieldOfView` properties could be upstreamed to a future version of the the Media Capture and Streams specification [GETUSERMEDIA] to allow them to be applied to video `MediaStreamTrack` objects as well.
