### ISSUE TITLE
Support a consistent measurement unit

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-depth#113]
We support i420 and RGB for video without burdening applications with the distinction between the two.  In the browser itself, those two might be carried differently, but when they hit a screen or API, they are converted to a common form.

It would appear that depth captures aren't consistent in the units they use.

I can understand a representation that was expressed relative to the focal length or some other physical constraint if the intent is to preserve the maximum dynamic range over the 8 or 16 bits available to the encoding, but the spec already does that in terms of the near and far value.

The near value and far value in particular could be expressed in metres.

**Comment by anssiko** [comment]
#111 is consistent in depth value representation, and standardizes on millimeters. I'm hearing this is the unit that the native APIs use to represent depth.

**Comment by anssiko** [comment]
We eventually settled on meters (using this U.S. English spelling in the spec assuming the [W3C Manual of Style](https://www.w3.org/2001/06/manual/#Translations) is to be obeyed still).

Specifically, fixed this issue with 13c5bda in #118, as discussed in #114.
