### ISSUE TITLE
Range constraints

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#114]
Creating a standalone issue for this discussion started in #100:

> @jan-ivar:
> I naively imagine I'd probably want a different setting for pointing my kinect out my window vs. pointing it at my couch?
> 
> @martinthomson:
> @jan-ivar, that would be a separate constraint, probably two.  minimumRange: 1, maximumRange: 100.  If that's a real concern, then a separate issue.  For this one, I think that @anssiko has the right approach: find out how do the devices actually measure and work from there.
> 
> @huningxin:
> @jan-ivar, Kinect SDK allows to configure depth camera range (`Default` or `Near`) [[1]](https://msdn.microsoft.com/en-us/library/microsoft.kinect.depthimagestream.range.aspx). libealsense [[2]](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rsutil.h#L107) allows to configure several ranges to RealSense front facing depth camera as well (`Common`, `ShortRange`, `LongRange` etc.,).  I am not aware Tango SDK allows to configure working range of its depth camera.

**Comment by martinthomson** [comment]
As long as these different configuration options leave the browser able to determine the resulting range, then I think that's fine.  I think that having constraints on `near` and `far` would be good. ConstrainDouble seems right.  I can imagine that users will probably only set a maximum `near` and minimum `far`, though I imagine cases where a shorter or longer overall range might be good.

**Comment by anssiko** [comment]
(Copying feedback from #100 that is relevant to this issue here:)

@martinthomson [said](https://github.com/w3c/mediacapture-depth/issues/100#issuecomment-201134737):

> 1. use metres
> 2. the form is `{ depthNear: { min: 0, max: 2 }, depthFar: { ideal: 5 } }`
> 3. we should be able to use the constraints in two ways:
>    - to pick the camera mode that best fits, and
>    - to adjust the range over which the value is converted to the 8-bit value

@alvestrand [said](https://github.com/w3c/mediacapture-depth/issues/100#issuecomment-201944954):

> Adjusting near and far as constraints seems good to me.
> The main purpose of near and far is driving the conversion algorithm.
> 
> The camera driver would then use the settings on the particular device that make the most sense with those constraints - ie it would set "shortRange" on the RealSense if a "far" of less than (say) 1m was acceptable to the user.
> 
> In a later version, I would think that adding a way to get something deeper than an 8-bit map makes sense - since most video codecs are growing 10, 12 and even 14 bit modes these days, there will be other people clamoring for such an option too. But that's a different topic.
