### ISSUE TITLE
Drop range linear conversion, always use range inverse conversion

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#115]
Currently shipping depth cameras (see https://github.com/w3c/mediacapture-depth/issues/100#issuecomment-200236879) all use a native depth value format with a bit depth greater than 8.

To simplify the conversion, perhaps we should just drop the range linear conversion and standardize on the range inverse conversion. In practical terms, modify the steps 4 and 5 in [convert the depth map value to grayscale](https://w3c.github.io/mediacapture-depth/#dfn-convert-the-depth-map-value-to-grayscale) as follows:

> 1. <strike>If bit depth is greater than 8, then</strike> apply the rules to convert using range inverse to d to obtain quantized value d<sub>8bit</sub>.
> 2. <strike> Otherwise, apply the rules to convert using range linear to d to obtain quantized value d<sub>8bit</sub>.</strike>

This also simplifies the conversion from quantized depth to depth measurement in mm the web developer must take care of, removes the need to branch for linear/inverse, see #112.

**Comment by anssiko** [comment]
To add, the con is that at the far end of the range there's more error using range inverse vs. range linear conversion. See [mediacapture-depth error of measurement from conversion](https://docs.google.com/spreadsheets/d/110b3bYUwVmhou92hs5D0ClfypI4QDqCWiQBV_3-aDC4/pubhtml?gid=0&single=true) for some example data.

On the pros side we have better web developer ergonomics.

**Comment by bbernhar** [comment]
LGTM

**Comment by huningxin** [comment]
LGTM. Thanks for this PR!

**Comment by anssiko** [comment]
@huningxin @bbernhar Thanks for the review. Fix landed & issue closed.
