### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by publicocean0** [w3c/mediacapture-depth#121]
hi ... I might develop a MediaStream class that receiving data not from camera but from a websocket stream. 
The idea is to create my WSMediaStream extends MediaStream in javascript. it is possible to pass to peer.addStream this kind of class for your opinion?
thanks for suggestion

**Comment by anssiko** [comment]
`PeerConnection` is considered out of scope of v1, see #12 for more details.

**Comment by publicocean0** [comment]
We need a long native number  integer 64bit. The time is mature

Inviato da iPad
