### ISSUE TITLE
The XDM reference and related text should be removed

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-depth#134]
It's not used in anyway so I don't see why it is here

**Comment by huningxin** [comment]
Thanks for reporting this issue. It was referred in previous version. Now the usage goes away. We need to remove it in latest version.

**Comment by robman** [comment]
OK but we do need to explore the intrinsics and extrinsics and XDM is a good reference implementation to point to here. At the moment we don't even know the vector between the camera and IMU on mobile devices (or integrated devices like Tango/Hololens/Alloy) which is a real issue.

**Comment by fluffy** [comment]
I wonder if we could report a camera direction vector (in cases where it is known) ? Should we open an issue for that ?

**Comment by huningxin** [comment]
> I wonder if we could report a camera direction vector (in cases where it is known) ?

@fluffy , do you mean the camera pose information?

For example, some of Intel realsense cameras provide the motion data which has accelerator and gyro readings. It is a kind of integrated IMU of the 3D camera.

**Comment by robman** [comment]
I was going to remove the XDM reference but we ref to it for the range linear format so leaving it in place. 

Unless anyone objects I think we can close this and move any camera extrinsics/direction/pose discussions to a new issue.

**Comment by anssiko** [comment]
Sounds fine, @robman could you open a new issue for the camera extrinsics/direction/pose discussions?

**Comment by anssiko** [comment]
Proposed fix #141.

**Comment by fluffy** [comment]
Should we open a new bug for camera pose. If you can get video from left and right camera, it often nice to have relative location information of them too. For example, we make a 3 camera head that has three camera that all point slightly different direction. We also make pan tilt units where we can report the pose. Of things like http://www.cisco.com/c/en/us/products/collateral/collaboration-endpoints/telepresence-speaker-track-60/datasheet-c78-729836.html .

**Comment by anssiko** [comment]
@fluffy please open a new issue and include your details, thanks!

**Comment by robman** [comment]
Camera pose should fit under extrinsics and I think there's at least 3 main contexts:
- fixed cameras (pre-defined fixed pose)
- articulated cameras (as in the telepresence setup @fluffy describes above)
- mobile computer vision (as in a Tango mobile device, Hololens, Alloy, etc.)

For use in AR/VR these all need to be transformed into some sort of world coordinate system too.

+1 to moving all the intrinsics and extrinsics discussion into #110
