### ISSUE TITLE
Need an invalid value 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-depth#137]
This bug is important to fix before this goes for wider review. 

Most depth sensors may not product a depth for every pixel. It is important that when they can no detect what the depth value is at a give location, they can report that there is no reading vs reporting a bad reading. We need to define a way a value that indicates "no depth detected". Typically this is zero. Once we define this value, then the near / far distance calculations formulas need to be adjusted.

**Comment by huningxin** [comment]
+1. Most native SDK defines the invalid value. We should generalize that for Web.

**Comment by robman** [comment]
The standard for `unknown depth` seems to be 0 which makes sense to me - lets just go with that.

**Comment by huningxin** [comment]
+1 to define zero as "no depth".  This is a reasonable sentinel for "no depth" because all pixels with a depth of zero would correspond to the same physical location, the location of the imager itself.

**Comment by anssiko** [comment]
See #139 for a proposed fix.
