### ISSUE TITLE
(16-bit) Grayscale conversion of (16-bit) depth map is wrong

### ISSUE THREAD

**Issue by astojilj** [w3c/mediacapture-depth#142]
With the time, the "depth map" changed the meaning from abstraction of real world distance to a 16-bit representation of depth. This part of spec remained and now is wrong - it reads as it converts 16-bit depth map to 16-bit grayscale?
Grayscale should be 8 bit, not 16-bit.

The text states:

> The **data type of a depth map is 16-bit** unsigned integer. The algorithm to convert the depth map value to grayscale, given a depth map value d, is as follows:
> 
> Let near be the the near value.
> Let far be the the far value.
> Apply the rules to convert using range linear to d to obtain quantized value **d16bit.**
> Return **d16bit.**
> 

from video:

> 6.6 The video element
> 
> When a video element is potentially playing and its assigned media provider object is a depth-only stream, the user agent must, for each pixel of the media data that is represented by a depth map, given a depth map value d, convert the depth map value to grayscale and render the returned value to the screen.
> 
> NOTE
> It is an implementation detail how the frames are rendered to the screen. For example, the implementation may use a grayscale or red representation, with either 8-bit or 16-bit precision.
>

**Comment by robman** [comment]
+1 to 8bit grayscale

**Comment by huningxin** [comment]
The change was introduced by https://github.com/w3c/mediacapture-depth/pull/130.

+1 to 8bit grayscale too. 

I suppose 8bit grayscale is still good for 8bit surface, like video->imageData and RGB/UNSIGNED_BYTE WebGL uploading. We should bring it back.

> Grayscale should be 8 bit, not 16-bit.

Y16 is one kind of 16bit grayscale. 

The 16bit grayscale conversion is good for R16UI and Float WebGL uploading.

**Comment by mkollaro** [comment]
I find the term "16bit grayscale" a bit meaningless. What is the difference between the 16bit raw data before the conversion, and the 16bit grayscale? PC screens can show only an 8bit grayscale anyway. Maybe you meant something like a normalization based on Near and Far, instead of "conversion to grayscale"?

**Comment by astojilj** [comment]
The section could be replaced altogether by e.g. a link to definition in OpenGL ES 3.0 (WebGL2) specification:
https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf

2.1.6.1 ConversionfromNormalizedFixed-PointtoFloating-Point 
2.1.6.2 ConversionfromFloating-PointtoNormalizedFixed-Point 

This is because we don't actually need to expose the information that the depth is 16-bit (and we don't do it via API) but we follow WebGL specification that the same value can be expressed as.
Note that we should probably remove any mention of 16-bit values from the spec as there is no need to force it. This would be aligned to media capture + video HTML5 API in general as there is no mention of video bit depth: 8-bit and HDR-10 bit are already implemented (at least in Chromium) and the access to color components information is the same - if user uses 8-bit API (Canvas or WebGL) there is obvious data loss (if the video is HDR-10).

The depth map value captured from the original device can be, using HTML5 canvas or WebGL API be expressed using various different formats and the value needs to be consistent regardless of the form used to represent it:

1. normalized fixed point
   a. 8-bit is accessible if using 2D canvas API or if user uploads depth video to UNSIGNED_BYTE texture.
   b. 16-bit format (is original for 16-bit depth capture) but at the moment is not accessible through the API in original form.[ There is a proposal to create ](https://bugs.chromium.org/p/chromium/issues/detail?id=624436#c58)WebGL EXT_texture_norm16 extension to expose this - as float/half float is available on all relevant platforms we should probably do it first before starting the work on extension.
  c. 10-bit format if using RGB10_A2 WebGL texture.
2. float format - if using GL_FLOAT texture
3. half-float format  - if using GL_HALF_FLOAT texture.

I'll make a PR for this.
