### ISSUE TITLE
Change depth to MediaTrackConstraints

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#143]
Current spec defines the depth as a new media type in `MediaStreamConstraints`

```
partial dictionary MediaStreamConstraints {
    (boolean or MediaTrackConstraints) depth = false;
};
```

However actually the depth camera is a kind of video capture device, it shares most of characteristics of a color camera. The major difference with a color camera is the pixel format and the meta data describing the pixel value (depth value).

So I propose to change the depth to the `MediaTrackConstraints`. To accommodate more kinds of video capture device, it would introduce the `videoKind` constrainable property:

```
partial dictionary MediaTrackConstraintSet {
             ConstrainDOMString videoKind;
};

enum VideoDeviceKindEnum {
    "color",
    "depth",
    "infrared",
    "fisheye"
};
```

The example of requesting a single depth track:
```
navigator.mediaDevices.getUserMedia({
  video: {videoKind: {exact: "depth"}}
}).then(function (stream) {
  // Render the depth video.
  var video = document.querySelector('#depth-video');
  video.srcObject = stream;
  video.play()
});
```

The example of requesting the color and depth tracks from one 3D camera by setting the `groupId` of the 3D camera.
```
navigator.mediaDevices.getUserMedia({
  video: {groupId: {exact: id}}
}).then(function (stream) {
  // Render the color video.
  var video = document.querySelector('#color-video');
  video.srcObject = stream;
  video.play()
});

navigator.mediaDevices.getUserMedia({
  video: {videoKind: {exact: "depth"}, groupId: {exact: id}}
}).then(function (stream) {
  // Render the depth video.
  var video = document.querySelector('#depth-video');
  video.srcObject = stream;
  video.play()
});
```

@robman @anssiko @fluffy @astojilj,  WDYT?

**Comment by robman** [comment]
+1 - I agree it's a class of video capture devices (e.g. sensor that emits a stream of images/video)

Not 100% on the label videoKind but it is accurate and that's just bikeshedding 8)

**Comment by robman** [comment]
@huningxin should we add `measureType` (see #80 ) into the constraints here too?

**Comment by astojilj** [comment]
+1. Thanks.

**Comment by huningxin** [comment]
> Not 100% on the label videoKind but it is accurate and that's just bikeshedding 8)

@robman Do you have any suggestions? :)

**Comment by huningxin** [comment]
> @huningxin should we add measureType (see #80 ) into the constraints here too?

Provided comments to #80. Sorry for late response.

**Comment by anssiko** [comment]
+1. This proposal future-proofs the API for additional video capture devices and makes the API for grouping of multiple devices more explicit reusing the `groupId` concept defined in mediacapture-main. As a tradeoff it makes the common case of requesting stream(s) is a bit more verbose, but that is a minor issue we can like with.

@huningxin can you stage a PR to address this issue that we could review?

**Comment by huningxin** [comment]
OK. I am going to stage a PR and let you review.
