### ISSUE TITLE
Improve constrainable properties sections

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#159]
* We now link directly from the dictionary IDL members to the "Constrainable properties" sections where the expected behaviour for each dictionary member per kind (color or depth) should be defined. Ensure each of the constraints in these sections is defined properly.

* Editorial: convert the "constrainable properties" tables to simple prose. The tables make the columns too narrow for text, also "Notes" column contains normative assertions which is confusing. Prefer the format in https://w3c.github.io/mediacapture-image/#constrainable-properties over https://www.w3.org/TR/mediacapture-streams/#constrainable-properties.

**Comment by yell0wd0g** [comment]
@anssiko I had a similar issue when porting mediacapture-image to Constrainable Pattern.  Bikeshed is a delight for these matters.  I volunteer to port this Spec to Bikeshed if the editors are interested -- and we could remove that table that is indeed hard to read 😄

**Comment by anssiko** [comment]
I think I managed to get reasonable results in #160 by removing the tables and using a dirty CSS hack to hide duplicate dfns. So let's see if we can resist porting a while longer, thanks for the offer anyways :-) We have a MathJax dependency with a custom build step in the spec, so porting might not be straight-forward in this case.

I use Bikeshed for some other specs, and agree it is more flexible in many ways. I actually think mediacapture-main would benefit from Bikeshed port the most. Some issues I've run into with it:

* Broken fragments in the ED, making it hard/impossible to reference the latest ED from other specs that extend it. Must reference the snapshots instead but they are sometimes out-of-sync.

* Editorial issues such as the above-mentioned tables, and duplication of definitions that could be fixed easily with Bikeshed.
