### ISSUE TITLE
Publish an updated Working Draft

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#163]
Note to self: given the recent spec updates to make it more complete, we should publish an updated Working Draft as soon as possible.

Publication blocked on https://github.com/w3c/respec/issues/1163#issuecomment-293822204

**Comment by deniak** [comment]
I've added a temporary exception to pubrules and echidna so these specific CSS errors don't block the publications.

**Comment by anssiko** [comment]
Thanks @deniak! Your temporary workaround unblocked this issue, and a new WD was just published:

https://www.w3.org/TR/2017/WD-mediacapture-depth-20170418/
