### ISSUE TITLE
Point to public-webrtc

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-depth#164]
Intro currently says comments should be brought to the (to be discontinued) public-media-capture list.

**Comment by astojilj** [comment]
> (to be discontinued)
There is no intent to mark mediacacpture-depth as discontinued. What is the action required from mediacapture-depth editors? Thanks.

**Comment by anssiko** [comment]
@stefhak is suggesting we replace all occurrences of "public-media-capture@w3.org" with "public-"webrtc@w3.org".

The public-media-capture@w3.org *mailing list* is to be discontinued, not this work.

**Comment by astojilj** [comment]
Thanks @anssiko. No drama here then.
