### ISSUE TITLE
What happens in addTrack(mst) if mst.kind == 'depth'?

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#18]
FPWD CfC feedback from Bernard Aboba from Microsoft http://lists.w3.org/Archives/Public/public-media-capture/2014Sep/0106.html.

**Comment by robman** [comment]
For phase1 this would probably throw an error.

Of course under phase1 you could also use srcObject to cast a kind=depth to kind=video - but as far as I'm aware you still can't get a stream back out of an HTMLVideoElement once you've cast it - so you can't then use it in addTrack.

If you could then the (RG)BA data would be sent like any normal video stream - however the 16 bit depth values will most likely be mangled in some way by whichever codec is used.

We'll deal with this in more detail in phase2.
