### ISSUE TITLE
Add depth unit and range capabilities

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#2]
They are depth camera [Capabilities](http://dev.w3.org/2011/webrtc/editor/getusermedia.html#capabilities). For example, a depth camera can sense depth value in 1 mm precision, from 150 mm to 3000 mm.

**Comment by robman** [comment]
We'll deal with this in phase2.

**Comment by anssiko** [comment]
Addressed by:
http://w3c.github.io/mediacapture-depth/#dom-mediatrackconstraints-unit
http://w3c.github.io/mediacapture-depth/#dom-mediatracksettings-near
http://w3c.github.io/mediacapture-depth/#dom-mediatracksettings-far
