### ISSUE TITLE
What is the minimum set of metadata CameraParameters should expose

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#27]
At minimum, the general pinhole camera model have to be calculable. For related discussion, see the Focal length/fov capabilities and general camera intrinsics thread (http://lists.w3.org/Archives/Public/public-media-capture/2014Jun/0113.html).

[Issue copied from the spec into GH issues.]

**Comment by robman** [comment]
I've done quite a bit of work reviewing the maths on this to make sure we really are covering all the needs for the pinhole camera model.
http://en.wikipedia.org/wiki/Pinhole_camera_model

Interestingly Tango have an excellent page on their API here.
https://developers.google.com/project-tango/overview/intrinsics-extrinsics

This is obviously different from the Android API for example.
http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getFocalLength%28%29

e.g. f vs fx/fy

f is more for use in the geomteric model and is the normal line between the focal point and the image plane - the proportional inverse of the camera's Point Of View (X3).

fx/fy are actually used in the intrinsic matrix.

See this info on "Camera resectioning" for more information.
http://en.wikipedia.org/wiki/Camera_resectioning

The short story is, we can certainly reconstruct focalLengthX/focalLengthY from focalLength,horizontalViewAngle,verticalViewAngle,width and height.

So I'm comfortable that with focalLength, horizontalViewAngle, verticalViewAngle along with the existing width, height and aspectRatio we have all the params we need - and can reconstruct any others required.
