### ISSUE TITLE
Define the algorithms for the createDepthData(), getDepthData(), and putDepthData() methods

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#28]
We may want to file bugs against [2DCONTEXT2] to add extension points this specification can hook into to facilitate reuse of common algorithms and avoid monkey patching.

[Issue copied from the spec into GH issues.]

**Comment by anssiko** [comment]
Thread at http://lists.w3.org/Archives/Public/public-canvas-api/2014OctDec/0021.html seems to suggest we should use http://lists.w3.org/Archives/Public/public-canvas-api/ for feedback with regard to extensions to the CanvasRenderingContext2D interface.

**Comment by anssiko** [comment]
Rik suggests on [public-canvas-api](http://lists.w3.org/Archives/Public/public-canvas-api/2014OctDec/0034.html) to create a new canvas context type rather than extending the CanvasRenderingContext2D with the new methods.

**Comment by robman** [comment]
Basically addressed in phase1.
More detailed handling of this will be defined as part of the DepthData object in phase2.
