### ISSUE TITLE
Read back into an existing Uint16Array, instead of allocating a new one each time

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#29]
Elsewhere, Kenneth Russell proposed:

> One comment: for the 2D canvas context, I'd suggest you consider
> changing getDepthData to read back into an existing Uint16Array,
> instead of allocating a new one each time.

Related section: http://w3c.github.io/mediacapture-depth/#depthdata-interface

**Comment by robman** [comment]
We'll deal with this in phase2.

**Comment by anssiko** [comment]
`getDepthData()` and `DepthData` have been deprecated and are reworked, closing.
