### ISSUE TITLE
Support depth camera in Enumerating Local Media Devices of media capture spec

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#32]
http://w3c.github.io/mediacapture-main/getusermedia.html#enumerating-devices

Support `depthinput`in MediaDeviceKind (http://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaDeviceKind)

**Comment by huningxin** [comment]
This was raised in TPAC session.

**Comment by robman** [comment]
We'll deal with this in phase2.

**Comment by anssiko** [comment]
Fixed with ee8f7ae.
