### ISSUE TITLE
Specify the depth stream to WebGL uploading

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#4]
Upload depth image (Uint16Array, 16bpp) as texture to WebGL.

**Comment by huningxin** [comment]
One related discussion in WebGL WG is https://www.khronos.org/bugzilla/show_bug.cgi?id=407

**Comment by huningxin** [comment]
https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_texture_from_depth_video/

**Comment by huningxin** [comment]
For WebGL 1.0, this is done. Please open another issue for anything need to follow up.

**Comment by anssiko** [comment]
For the record, an informative reference to this WebGL extension was added to the W3C spec in https://github.com/w3c/mediacapture-depth/commit/8482ace0cbccec7f349df24f3b9de7dfefe6a61f
