### ISSUE TITLE
View angle sounds weird, and it probably should be 'viewing angle' instead

### ISSUE THREAD

**Issue by kenchris** [w3c/mediacapture-depth#56]
SSIA (subject says it all)

**Comment by robman** [comment]
Actually Field of View is probably the more standard term in the Computer Vision domain.
http://en.wikipedia.org/wiki/Field_of_view

So I'd be happier with horizontalFieldOfView and verticalFieldOfView.

**Comment by kenchris** [comment]
That sounds good to me
