### ISSUE TITLE
Add depth context of HTML canvas element

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#67]

**Comment by ds-hwang** [comment]
could you point out mailing list or discussion related to this issue?

**Comment by anssiko** [comment]
I think the proposal can be attributed to Rik: https://lists.w3.org/Archives/Public/public-canvas-api/2014OctDec/0034.html

**Comment by huningxin** [comment]
As we made consensus on this one, can i close it?

**Comment by ds-hwang** [comment]
+1

**Comment by anssiko** [comment]
Please feel free to close this, I closed the related PR https://github.com/w3c/mediacapture-depth/pull/68
