### ISSUE TITLE
Add more depth relevant attributes into Settings interface

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#72]
Reference is: https://developers.google.com/depthmap-metadata/reference

Proposal is:

```
partial dictionary Settings {
    readonly attribute string type;
    readonly attribute string format;
    readonly attribute string units;
    readonly attribute float  near;
    readonly attribute float  far;
};
```

**Comment by anssiko** [comment]
It seems we should expose `Settings` via the `ImageCapture` interface and reuse the accessors it provides.

I suggested changes to the accessors of the mediacapture-image, see: https://lists.w3.org/Archives/Public/public-media-capture/2015Mar/0048.html We should update http://w3c.github.io/mediacapture-depth/#settings-dictionary accordingly when the suggested changes land to the mediacapture-image.

**Comment by anssiko** [comment]
Closed via https://github.com/w3c/mediacapture-depth/pull/77
