### ISSUE TITLE
Update implementation considerations re track synchronization and calibration 

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#75]
Currently we have the following non-normative section in the spec: http://w3c.github.io/mediacapture-depth/#implementation-considerations

> A MediaStreamTrack object representing a video track and a MediaStreamTrack object representing a depth track can be combined into one MediaStream object. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources.

With the currently defined API we can create a depth-only MediaStream `s2` out of the combined "RGB and depth" MediaStream `s` and assign `s2` to `<video>` element `v` as follows:

```
var s2 = new MediaStream(s.getDepthTracks()[0]);
v.src = URL.createObjectURL(s2);
```

Any implementability issues in keeping the RGB stream synchronized and calibrated with the depth stream if they are combined into a single MediaStream versus split into two MediaStreams as long as they originate from the same MediaStream initially?

Referring back to https://www.w3.org/wiki/Media_Capture_Depth_Stream_Extension#Requirements it seems we attempt to address LMD4 and LMD5 but only for a combined MediaStream.

Can we rephrase implementation considerations to apply to cases in which the combined stream is split into two MediaStreams? IOW as long as the tracks originate from the same MediaStream best effort would be taken to keep them synchronized and calibrated. I think this would be the expectation of web developers, but may be hard to implement as it requires coordination between MediaStreams.

**Comment by ds-hwang** [comment]
First of all, we must need to support split into two MediaStreams, because some cases only need depth stream and others only need video stream. For example, gesture control needs only depth stream, and someone uses RealSense as just cam.
Furthermore, we want it possible to draw depth stream on video element, which means some cases want to make video element draw depth stream and others  want to make video element draw video stream.

However, combined single VideoElement is not necessary. It provides just additional convenience. I'm not fan of combined single VideoElement because
1. visual result of combined single VideoElement is just same to VideoElement based on video stream
2. It requires additional implementation changes. Blink video code must deal with combined video, just video, and depth video.

I think combined single VideoElement doesn't require huge architecture change. It just add additional complexity to code. It might be better to postpone to next stage.

Synchronization might bring up combined single VideoElement. It's straightforward to synchronize video stream VideoElement and depth stream VideoElement because the source is same, which means the video and depth frame is decoded together.
If user plays video stream VideoElement but stops depth stream VideoElement, implementation just drop depth frames until user plays depth stream VideoElement. Both are always synched.

In chromium video implementation, one VideoElement has one Pipeline, which provides video frame.
![Alt text](http://www.chromium.org/_/rsrc/1304732546623/audio-video/ChromiumMediaPlayerFSStack%20%281%29.png)

To support depth video, two VideoElement have to share one Pipeline, because source of video and depth stream is same and one Pipeline should produce both video frame and depth frame.

**Comment by huningxin** [comment]
> Can we rephrase implementation considerations to apply to cases in which the combined stream is split into two MediaStreams?

Combined stream is for LMD4 and LMD5. As my understanding, the splitting into two MediaStreams is a workaround that we didn't have API extension to extract both rgb image and depth image from the combined stream. One attempt is https://github.com/w3c/mediacapture-depth/issues/73 which extends video&canvas pipeline. Another attempt is https://github.com/w3c/mediacapture-depth/issues/76 which extends mediastream image capture pipeline. If we get https://github.com/w3c/mediacapture-depth/issues/76 solved, I don't think we need splitting solution for LMD4 and LMD5.

> First of all, we must need to support split into two MediaStreams, because some cases only need depth stream and others only need video stream.

Depth only use case only requires `getUserMedia({depth: true})`.
Color only use case only requires `getUserMedia({video: true})`.

**Comment by ds-hwang** [comment]
> Depth only use case only requires getUserMedia({depth: true}).
> Color only use case only requires getUserMedia({video: true}).

ah, that's right. so, why do we need to support split into two MediaStreams? @anssiko

**Comment by anssiko** [comment]
> so, why do we need to support split into two MediaStreams?

This is not a requirement in order to implement the use cases identified, since the standalone RGB and depth streams can be requested separately as @huningxin noted, but rather an API consistency issue. Web developers can split RGB-only `MediaStream` that contains multiple video tracks as follows:

```
var s2 = new MediaStream(s.getVideoTracks()[0]);
v.src = URL.createObjectURL(s2);
```

And they likely expect the same to work for RGB+depth, but using the `getDepthTracks()` that returns a sequence of `MediaStreamTrack` objects representing the depth tracks:

http://w3c.github.io/mediacapture-depth/#mediastream-interface

... and provide it to `MediaStream()` constructor to compose a new stream:

http://w3c.github.io/mediacapture-main/#mediastream-constructor

If this must not be possible, we need to monkeypatch the above `MediaStream()` constructor algorithm.

**Comment by bbernhar** [comment]
@huningxin
What is the use-case for where it is beneficial for a depth-stream to be wired to a &lt;video&gt; (e.g. a user wants a live feed of the depth-stream)? It seems that existing capture mechanisms can accomplish this indirectly and would avoid a separate rendering implementation where a source is not provided through the existing native media API.

**Comment by anssiko** [comment]
@bbernhar thanks for revisiting this issue. IIRC the rationale for including the [direct assignment to media elements](https://w3c.github.io/mediacapture-depth/#direct-assignment-to-media-elements) section was to enable similar API behavior regardless of what kind of tracks the `MediaStream` contains (as spec'd in [MediaStreams in Media Elements](http://w3c.github.io/mediacapture-main/getusermedia.html#mediastreams-in-media-elements) in mediacapture-main). Now revisiting this, I believe we still do not have a good use case, and implementations should handle combined RGB+depth `MediaStream` as if it contained just the RGB track if assigned to `<video>`. That is, there should be no `VideoTrack` in `HTMLMediaElement.videoTracks` that corresponds to the `MediaStreamTrack` of kind `depth`.

Spec-wise, we should be silent on how to render a `MediaStream` that contains depth track(s), and drop the related requirements.

I'll prepare a PR to drop the [Direct assignment to media elements](https://w3c.github.io/mediacapture-depth/#direct-assignment-to-media-elements) from the spec.

Rationale:
- No obvious use case for rendering the `MediaStream` that contains depth track directly on `<video>`.
- Can be achieved indirectly by mapping the depth map to RGB, e.g. into a grayscale representation to be rendered in `<video>` as defined by [mediacapture-main](http://w3c.github.io/mediacapture-main/getusermedia.html#mediastreams-in-media-elements).

**Comment by huningxin** [comment]
@bbernhar @anssiko , thanks for revisiting this!

I would argue to keep the [direct assignment to media elements](https://w3c.github.io/mediacapture-depth/#direct-assignment-to-media-elements).

The use case is depth camera preview. It would be a good utility, not only for developers but also for end users, to get the live feedback of what the depth camera is capturing. When you check the existing depth camera native samples, most of them provide the depth camera preview capability. 

From implementation perspective, wiring the depth stream to `<video>` element would have good performance for preview, as it is handled totally in native. Even later we have video-worker implemented, for depth camera preview use case, that solution has JS execution overhead and potential memory copies comparing to using `<video>`.

> Can be achieved indirectly by mapping the depth map to RGB, e.g. into a grayscale representation to be rendered in <video> as defined by mediacapture-main.

@anssiko , I think this is just specified by [direct assignment to media elements](https://w3c.github.io/mediacapture-depth/#direct-assignment-to-media-elements), is it?

**Comment by bbernhar** [comment]
@huningxin , of course :)

> The use case is depth camera preview. It would be a good utility, not only for developers but also for end users, to get the live feedback of what the depth camera is capturing. When you check the existing depth camera native samples, most of them provide the depth camera preview capability.

This use case can be already accomplished through indirect capture. Even so, it's only been rationalized as convenient for illustrative purposes. Equivalently could be shown through samples of our own. There remains a continuity argument for consistent API usage but it isn't for free.

> From implementation perspective, wiring the depth stream to element would have good performance for preview, as it is handled totally in native. Even later we have video-worker implemented, for depth camera preview use case, that solution has JS execution overhead and at least two more memory copies comparing to using.

Whether or not a depth stream is a preview or directly wired, it does not limit us in exposing a performant capture mechanism. I do see benefit in allowing capture without a video-worker as well, but it's orthogonal to direct assignment.

**Comment by huningxin** [comment]
I am open for a performant capture mechanism for depth stream. Actually, this is the reason we turn to depend on video-worker spec. However, as my understanding, they are all for depth track post-processing. To display a depth track, direct assignment to a &lt;video&gt; looks straightforward. Let's say video track, I expect even with video-worker shipped, developers will still use &lt;video&gt; for preview and use video-worker mainly for post-processing. I believe a similar API for depth stream would be easy to developers and would have a performant implementation in browser as well.

Even for post-processing use case, I think keeping direct assignment would allow to use today's &lt;video&gt; -> &lt;cavans&gt;/WebGL pipeline. Let's think about that a browser implements mediacapture-depth but no video-worker. The web app is able to do depth post-processing on 8-bit grayscaled depth value for some use cases which don't require full 16-bit depth value. Just like today's web app do CV on color video.

WDYT?

**Comment by huningxin** [comment]
BTW, @bbernhar , I am interested in your ideas about the capture mechanism without a video worker. Could you share more?

**Comment by anssiko** [comment]
@huningxin I just noticed that if we continue to allow direct assignment to media elements, then we also need to specify how does the `ImageData` object returned by the `getImageData()`method look like in the depth case. As you remember, we dropped the [CanvasRenderingContext2D extensions](http://www.w3.org/TR/2014/WD-mediacapture-depth-20141007/#canvasrenderingcontext2d-interface) we had in an earlier version of the spec.

Here's an excerpt:

```
context.drawImage(depthVideoElement, x, y, w, h);
var imageData = context.getImageData(x, y, w, h);
```

If the use case for direct assignment to media elements is only depth camera preview (e.g. for development and debugging purposes) and not reading the pixel values using the canvas indirection, one proposal how to address this to ensure interoperability would be to say:
- If the first argument passed to the `drawImage()` method on `context` is a `HTMLVideoElement` that contains a depth track only, then act as if the `clearRect(0, 0, context.width, context.height)` method was invoked on `context`.
- If the `HTMLVideoElement` contains both an RGB and depth track, act as if the `HTMLVideoElement` would contains just an RGB track.

This would mean that the `imageData` in the above example would represent a fully transparent black rectangle.

WDYT? We could state in the spec more clearly that for reading, the web developers are expected to use mediacapture-worker.

I'd also like to hear @bbernhar thoughts on capturing without a video worker. We've tried it before, but ran into issues. The latest proposals was the [FrameGrabber](https://w3c.github.io/mediacapture-depth/#framegrabber-interface) now at risk to be dropped in favor of the mediacapture-worker. Another attempt was to use the proposed [CanvasRenderingContext2D extensions](http://www.w3.org/TR/2014/WD-mediacapture-depth-20141007/#canvasrenderingcontext2d-interface), from which we also backed off.

**Comment by anssiko** [comment]
@bbernhar please feel free to open a new issue for discussing an incubating the idea for "allowing capture without a video-worker".

**Comment by huningxin** [comment]
> As you remember, we dropped the CanvasRenderingContext2D extensions we had in an earlier version of the spec.

If I remember correctly, the issue is that we proposed to extend CanvasRenderingContext2D to suport 16bit depth data. Obviously, canvas folks only want to suppose RGBA format. So we get pushed back. 

But for grayscaled depth video, there is no such issue.

For your cases:

> If the first argument passed to the drawImage() method on context is a HTMLVideoElement that contains a depth track only, then act as if the clearRect(0, 0, context.width, context.height) method was invoked on context.

No. This should draw a grayscaled depth image.

> If the HTMLVideoElement contains both an RGB and depth track, act as if the HTMLVideoElement would contains just an RGB track.

Agree. This should only draw the color image.

**Comment by anssiko** [comment]
@huningxin I think you recall the concerns from the canvas folks correctly.

> This should draw a grayscaled depth image.

I'd be fine with this. Then we just need to define the depth mapping to grayscale in mediacapture-depth. 

For advanced use cases that require more precision and/or better performance, web developers should use mediacapture-worker instead.

This would allow implementations to choose to implement only mediacapture-depth for simpler use cases, and in addition mediacapture-worker for advanced usages. Choice is a good thing.

**Comment by huningxin** [comment]
> Then we just need to define the depth mapping to grayscale in mediacapture-depth.

I think we can refer to https://developers.google.com/depthmap-metadata/encoding and https://software.intel.com/sites/default/files/managed/2a/f2/XDM-Specification.pdf for the detph value 8-bits encoding:

"
Two different formats are currently supported: RangeLinear and RangeInverse. RangeInverse is the recommended format if the depthmap will lose precision when encoded, e.g. when converting from float to 8-bit. It allocates more bits to the near depth values and fewer bits to the far values, in a similar way to how the z-buffer works in GPU cards.
"
- RangeInverse

Let d be the depth of a pixel, and near and far the minimum and maximum depth values considered. The depth value is first normalized to the [0, 1] range as:

![image](https://cloud.githubusercontent.com/assets/1005673/11271089/c6a5cef0-8efe-11e5-8754-8cfaf7a253d3.png)

then quantize to 8 bits as:

![image](https://cloud.githubusercontent.com/assets/1005673/11271120/f2899b0a-8efe-11e5-8150-4f99a700f9b0.png)

As we expose `far` and `near` in [MediaTrackSettings ](http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary), and given the normalized depth dn, web app can recover depth d as:
![image](https://cloud.githubusercontent.com/assets/1005673/11271160/3ca1af48-8eff-11e5-96ef-02f31cd96436.png)

> For advanced use cases that require more precision and/or better performance, web developers should use mediacapture-worker instead.
> 
> This would allow implementations to choose to implement only mediacapture-depth for simpler use cases, and in addition mediacapture-worker for advanced usages. Choice is a good thing.

Exactly!

**Comment by anssiko** [comment]
@huningxin Looks good. For mapping depth to the range 0..255 to be used in the `ImageData` grayscale representation, I suggest we add something like the following to the spec:

The _algorithm to convert a depth map value to the range 0..255_, given a depth map value _d_, is as follows:
- Let _bit depth_ be the bit depth of the depth map.
- Let _near_ be the the minimum range of that depth map.
- Let _far_ be the the maximum range of that depth map.
- If _bit depth_ is greater than 8, then apply the _rules to convert using range inverse_ to _d_ to obtain quantized value _d<sub>8bit</sub>_.
- Otherwise, apply the _rules to convert using range linear_ to _d_ to obtain quantized value _d<sub>8bit</sub>_.
- Return _d<sub>8bit</sub>_.

The _rules to convert using range inverse_ are as given in the following algorithm:

![](https://cloud.githubusercontent.com/assets/1005673/11271089/c6a5cef0-8efe-11e5-8754-8cfaf7a253d3.png)
![](https://cloud.githubusercontent.com/assets/1005673/11271120/f2899b0a-8efe-11e5-8150-4f99a700f9b0.png)

The _rules to convert using range linear_ are as given in the following algorithm:

![](https://developers.google.com/depthmap-metadata/images/normalize_linear.png)
![](https://cloud.githubusercontent.com/assets/1005673/11271120/f2899b0a-8efe-11e5-8150-4f99a700f9b0.png)

I can prepare a PR with this, if there are no concerns.

**Comment by bbernhar** [comment]
@huningxin

> However, as my understanding, they are all for depth track post-processing. To display a depth track, direct assignment to a `<video>` looks straightforward.

It does on the surface but wouldn't this imply a video element that was assigned to a depth stream could perform operations such as playback? Not all sources are provided through the same existing native media API and would require a separate rendering implementation just to allow this. Maybe we could restrict rendering operations needed for capture for depth streams that only contain a depth-track. For example, allow canvas indirection on `<video>` for preview use-case and not require the far more complex video-worker dependency. Perhaps this suggests there could be a better balance to treat a depth stream something between a media device and sensor.

**Comment by huningxin** [comment]
@anssiko 

> For mapping depth to the range 0..255 to be used in the ImageData grayscale representation, I suggest we add something like the following to the spec:

 +1

> Let near be the the minimum range of that depth map.
> Let far be the the maximum range of that depth map.

The `near` and `far` should be defined depth sensor's capability. They should be exposed as depth camera settings where we defined in [MediaTrackSettings ](http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary). If `near` and `far` are depth map specific, there are no places to store them. Thus developers cannot recover the depth value.

> If bit depth is greater than 8, then apply the rules to convert using range inverse to d to obtain quantized value d8bit.
> Otherwise, apply the rules to convert using range linear to d to obtain quantized value d8bit.

Then we need to add the `format` enum into the `MediaTrackSetting` with value `RangeInverse` and `RangeLinear`, like https://developers.google.com/depthmap-metadata/reference.

However, as the depth cameras we evaluated so far all generate depth value greater than 8 bits, probably it is simpler to just use `RangeInverse` algorithm.

> I can prepare a PR with this, if there are no concerns.

Thanks for this! No concerns, two comments above.

**Comment by huningxin** [comment]
@bbernhar 

> It does on the surface but wouldn't this imply a video element that was assigned to a depth stream could perform operations such as playback?

I think it should have same behavior as video track assignment to video element.

> Maybe we could restrict rendering operations needed for capture for depth streams that only contain a depth-track.

Agree. That aligns with the idea we talked in https://github.com/w3c/mediacapture-depth/issues/75#issuecomment-157999770 as
- if media stream contains depth track only, draw the grayscaled depth map with defined algorithm
- if media stream contains both video and depth track, only draw the color video frame

Does it look OK to you?

**Comment by bbernhar** [comment]
To summarize in code...

```
// Create combined media stream
navigator.mediaDevices.getUserMedia({
  depth: true,
  video: true
}).then(function (mediaStream) {
    var video = document.getElementById('videoTag');
    video.srcObject = mediaStream;
    video.play(); // direct playback allowed
    ...
    // Post-process video through canvas
    canvasContext.drawImage(video);  // implicitly default to color

    // Post-process depth through canvas indirection
    var depthVideo = document.getElementById('depthTag');
    var depthStream = new MediaStream(mediaStream.getDepthTracks()[0]);
    depthVideo.srcObject = depthStream;
    depthVideo.play() // direct playback NOT allowed
    ...
    canvasContext.drawImage(depthVideo); // grayscaled depth map with defined algorithm

    // Post-process through worker
    var depthTrack = mediaStream.getDepthTracks()[0];
    ... 
    resultDepthVideo.srcObject = new MediaStream([resultDepthTrack]); // separate processed result <video>
    resultDepthVideo.play(); // direct playback allowed on result <video>
}
```

This would allow post-processing of depth without workers and through direct assignment on an existing combined media stream. It requires a cloned depth-only media stream that is capture-only (no playback).

```
// Create depth-only media stream
navigator.mediaDevices.getUserMedia({
  depth: true,
}).then(function (mediaStream) {
    var depthVideo = document.getElementById('depthVideo');
    depthVideo.srcObject = mediaStream;
    depthVideo.play(); // direct playback NOT allowed
    ...
    // Post-process depth through canvas
    canvasContext.drawImage(depthVideo); // grayscaled depth map with defined algorithm

    // Post-process through worker
    var depthTrack = mediaStream.getTracks()[0];
    ... 
    resultDepthVideo.srcObject = new MediaStream([resultDepthTrack]); // separate processed result <video>
    resultDepthVideo.play(); // direct playback allowed on result <video>
}
```

Similar to above but doesn't require a combined media stream or indirection for capture through canvas.

@huningxin, @anssiko WDYT?

**Comment by huningxin** [comment]
@bbernhar , code is always helpful!

I don't quite get the reasons that `depthVideo` direct playback is NOT allowed. However the `resultDepthVideo` direct playback is allowed. 

To me, it is not good to depend on mediacapture-worker to do the depth video playback.

Others look perfect to me.

**Comment by bbernhar** [comment]
@huningxin 

I'll further clarify. :)

If the implementation does not use the same pipeline to provide both video and depth frames, there isn't a similar native way for playback and a separate rendering implementation is required. Video workers accomplishes this, but it's an unnecessary requirement given our use-cases are similarly achieved without. So, it seems more approachable to only require a capture-only mode depth stream given these implications. Unfortunately, this does not allow direct preview-like ability but does so to avoid these incompatibilities that could outright prevent an implementation without video workers.

**Comment by huningxin** [comment]
@bbernhar , for your information, In my early Chromium prototype (https://github.com/huningxin/chromium-crosswalk/blob/depth_stream/media/video/capture/win/video_capture_device_pxc_win.cc#L517), it converts the depth map to grayscaled RGBA image in video capture device immediately after capturing, then feed the grayscale image into exact media pipeline for playback. It doesn't require to modify media pipeline and video player.

Of course, in a sophisticated implementation, I need to extend the pipeline to support depth map format and convert to grayscale image when playback at video player. In this way, the media stream consumers (like video-worker) which supports depth map can get the 16-bits depth value.

**Comment by anssiko** [comment]
Updated the PR https://github.com/w3c/mediacapture-depth/pull/86 per recent discussion in this thread:
https://github.com/anssiko/mediacapture-depth/commit/94689731a917db26e3e06c1f35c5098ce38c9075

**Comment by anssiko** [comment]
Hearing no concerns, I merged https://github.com/w3c/mediacapture-depth/pull/86

I will close this issue. Please let me know if you think this should be reopened.

**Comment by bbernhar** [comment]
@huningxin 

Wouldn't that mean an existing and corresponding video device would have already configured the media pipeline to render the depth map? For depth-only stream preview (i.e. playback through `<video>`), there would be no such video device and would still require a separate playback implementation for other source providers. Unless of course, you always create a corresponding video device for capture and configure it for depth. This also means we must select which media sources from provider A correspond to depth sources from provider B that are from the same physical device.

At-least, this would allow a combined stream to achieve playback with the approach you suggest.

**Comment by huningxin** [comment]
> Unless of course, you always create a corresponding video device for capture and configure it for depth.

Yes. In my prototype, I always a depth video capture device when it is available.

> This also means we must select which media sources from provider A correspond to depth sources from provider B that are from the same physical device.

In native camera API, the depth camera and color camera (even packaged into one module, e.g. Intel R200 camera) are modeled to two different video capture devices. On some specially calibrated devices, developers are even able to use the color camera on system (out of R200) and the depth camera in R200 to capture the 3D photo.

**Comment by bbernhar** [comment]
@huningxin

On Windows, the native camera API operates only the video device which provides the color source. A separate API provides the depth in addition to another color source from the same module (sources must be from the same provider for coordinate mapping through the API).

The native camera API would configure the <video> pipeline for capture, but cannot be queried to identify if the corresponding depth device (it's source from a separate provider) belongs to the same module. Ideally, "groupId" would associate them but there isn't a module guid that would be the same between the devices. Wouldn't this be a native camera API requirement?
