### ISSUE TITLE
Extend Mediastream Image Capture to support depth track

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#76]
The proposal is:

```
[Constructor(MediaStream stream)]
interface ImageCapture {
    readonly    attribute PhotoCapabilities photoCapabilities;
    readonly    attribute MediaStream  videoStream;
    readonly    attribute MediaStream       previewStream;
    Promise setOptions (PhotoSettings? photoSettings);
    Promise takePhoto ();
    Promise grabFrame ();
};

partial interface FrameGrabEvent {
    readonly attribute DepthMap depthMap;
};
```
1. Modify the ImageCapture to take MediaStream object which may carry both video track and depth track.
2. Extend the FrameGrabEvent to include DepthMap object which is filled based on depth track when grabbing. The DepthMap interface is defined in https://github.com/w3c/mediacapture-depth/issues/66.

The sample code sketch looks like:

```
<html>
<body>
<button onclick="stopFunction()">Stop frame grab</button>
<script>
var canvas = document.getElementById('frame');
navigator.getUserMedia({video: true, depth: true}, gotMedia, failedToGetMedia);

function gotMedia(mediastream) {
   // mediastream carries both video track and depth track
   var captureDevice = new ImageCapture(mediastream);
   var frameVar;
   if (captureDevice) {
       frameVar = setInterval(captureDevice.grabFrame().then(processFrame()), 1000);
   }
}

function processFrame(e) {
  var imgData = e.imageData;
  var depthMap = e.depthMap;
  ASSERT(imgData.width == depthMap.width);
  ASSERT(imgData.height == depthMap.height);
  var w = imgData.width, h = imgData.height;
  var pixels = imgData.data, dexels = depthMap.data;
  for (var x = 0; x < w ; ++x) {
    for (var y = 0; y < h; ++y) {
      var i = x + y * w;
      var r = pixels[i*4];
      var g = pixels[i*4 + 1];
      var b = pixels[i*4 + 2];
      var depth = dexels[i]; // Uint16 depth value
    }
  }
}

function stopFunction(e) {
  clearInterval(frameVar);
} 
</script>
</body>
</html>   
```

**Comment by ds-hwang** [comment]
looks nice!

**Comment by huningxin** [comment]
@robman @anssiko , please take a look. Thanks!

**Comment by anssiko** [comment]
Thanks @huningxin for the proposal!

Since the `ImageCapture` constructor takes `MediaStreamTrack` as an argument, and not `MediaStream`, would it make sense to define a separate `DepthCapture` constructor instead that takes `MediaStreamTrack` as an argument and behaves as follows (similarly to mediacapture-image, but for "depth" instead of "video"):

> The `MediaStreamTrack` passed to the `DepthCapture` constructor must have its kind attribute set to "depth" otherwise an exception will be thrown.

Alternatively `DepthCapture`and `ImageCapture` could inherit from a `Capture` superclass if we'd benefit from reuse (requires coordination with the mediacapture-image editor):

```
interface Capture {
  // ...
};

interface DepthCapture : Capture {
    Promise grabDepthMap ();
  // ...
};

interface ImageCapture : Capture {
    Promise grabFrame ();
  // ...
};
```

Example using [Promise.all](http://www.w3.org/2001/tag/doc/promises-guide#aggregating-promises):

```
navigator.getUserMedia({video: true, depth: true}, gotMedia);

function gotMedia(ms) {
  // ms carries both video track and depth track
  var ic = new ImageCapture(ms.getVideoTracks()[0]);
  var dc = new DepthCapture(ms.getDepthTracks()[0]);

  setInterval(function() {
    Promise.all([ic.grabFrame(), dc.grabDepthMap()])
           .then(function(values) {
             // if both the promises are fulfilled, processFrame() is called
             processFrame({ imgData: values[0], depthMap: values[1] });
    });
  }, 1000);
}
```

**Comment by anssiko** [comment]
Noting the `mediastream.getDepthTracks()[0].getPixels()` proposal is functionally equivalent, but synchronous, see: https://github.com/w3c/mediacapture-depth/pull/68#issuecomment-75951586

**Comment by anssiko** [comment]
I'd like to get to a resolution which way to go for getting a depth map when given a depth track:

1) async API a la mediacapture-image
2) sync API  such as `getPixels()`
3) return a [ReadableStream](https://streams.spec.whatwg.org/#rs-class) from which each frame can be read

For consistency, should coordinate with mediacapture-image.

Only 3 guarantees each frame can be read.

@ds-hwang You mentioned you did not foresee issues in implementing 2 in Chromium given its current pipeline. Since a sync API would be simpler for web developers to use inside rAF or setInterval loops, that'd be preferred from API ergonomics point of view. However, would such a sync API potentially block the main thread in other implementations?

**Comment by huningxin** [comment]
> Example using Promise.all:

I suspect using `Promise.all` doesn't address aligned (a.k.a synchronized) video and depth stream use case.

In native camera SDK, such as Intel RealSense SDK and KinectSDK, it usually supports to capture the aligned video image and depth image (captured at same time) by one API call or one callback. The next call or callback probably results different frames. As video capture is continuous and internal buffer is limited, two JavaScript API calls for separate video image and depth image might be hard to be aligned.

The common capture work flow in native camera SDK is:
1. configure capture mode (color, depth or color+depth), resolution, frame rate etc.,.
2. start capture pipeline.
3. request a capture sample by an API call (synched) or via a callback (asynched).
4. data access: the returned capture sample carries either color image, depth image or color+depth images per configuration.

The capture sample can be defined like this in native SDK:

```
struct sample {
  RgbImage* rgb;
  DepthMap* depth;
};
```

It can use pointer NULL to indicate unused channel.

Back to web API, this work flow can be mapped to:
1. is done by `getUserMedia` constraints. Besides {'video': true} for color capture. We added {'depth': true} to specify depth capture. {'video': true, 'depth': true} for aligned color+depth use case.
2. is done by `new ImageCapture(stream)` in image capture pipeline. It takes `MediaStream` instead of `MediaStreamTrack` for aligned color+depth use case.
3. is done by 'grabFrame()`.
4. is done by extending `FrameGrabEvent` with `depthMap`. For {'video': true}, only `imageData` is populated. For {'depth': true}, only `depthMap` is populated. For {'video': true, 'depth': true}, `imageData` and `depthmap` are populated by aligned capture.

```
interface FrameGrabEvent : Event {
    readonly attribute ImageData imageData;
    readonly attribute DepthMap depthMap;
};
```

> Alternatively DepthCaptureand ImageCapture could inherit from a Capture superclass if we'd benefit from reuse (requires coordination with the mediacapture-image editor):

+1 to reach out mediacapture-image editor for feedback.

**Comment by anssiko** [comment]
[@robman indicated he has detailed feedback, but due to travel will be able to get to this in ~2 weeks from now.]

**Comment by anssiko** [comment]
Closed via https://github.com/w3c/mediacapture-depth/pull/77
