### ISSUE TITLE
Use VideoWorker and extend ImageBitmap to support depth

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#78]
We may want to replace `ImageData` and `DepthMap` with `ImageBitmap` to make use of the [mediacapture-worker](https://w3c.github.io/mediacapture-worker/) and [imagebitmap-extensions](https://w3c.github.io/mediacapture-worker/#imagebitmap-extensions) for depth data processing.

Some tasks we'd need to do if we go down this path:
- [x] Deprecate `DepthMap`
- [x] Use `ImageBitmap` with DEPTH ImageFormat instead of `DepthMap` for depth map in `FrameData`.

**Comment by huningxin** [comment]
@anssiko , thanks for opening this ticket. I suppose 

> Use ImageBitmap with GRAY16 color format instead of ImageData for depth map in FrameData.

should be "instead of `DepthMap` for depth map in FrameData".

**Comment by huningxin** [comment]
Sorry to close it by accident. Re-open it.

**Comment by anssiko** [comment]
@huningxin Thanks, fixed. Please feel free to create specific issues for concrete tasks and add them as dependencies (by simply referring #78 in task specific issues).

**Comment by anssiko** [comment]
The procedural things blocking this issue from progressing have been cleared:
- [x] The [mediacapture-worker](https://w3c.github.io/mediacapture-worker/) has been migrated to a [repo under the W3C GH org](https://github.com/w3c/mediacapture-worker) and the [imagebitmap-extensions](https://w3c.github.io/mediacapture-worker/#imagebitmap-extensions) was merged into the mediacapture-worker (see [PR](https://github.com/w3c/mediacapture-worker/pull/5)).
- [x] The W3C Media Capture TF [agreed to take mediacapture-worker](https://lists.w3.org/Archives/Public/public-webrtc/2015Aug/0075.html), with a long-term plan to move the spec to the Timed Media WG.

With that, let's resume work on mediacapture-depth starting with this issue.

@huningxin @robman @ds-hwang to get us (re)started:
- Are we fine with scoping mediacapture-depth to the [DedicatedWorkerGlobalScope](https://w3c.github.io/mediacapture-worker/#dedicatedworkerglobalscope-interface) initially? That'd allow us to build atop the mediacapture-worker and ship the spec update faster. In the possible next iteration we could then expose this to the main thread given good use cases and reasoning (would require us to add `onvideoprocess`to the `WindowEventHandlers` among other patches if we'd like to keep the API similar between worker and window).

I will take a stab at updating the spec based on your feedback in the coming days. We could also iterate the IDL simply in the issue comments first, so feel free to drop your proposals here.

We should have a good draft reflecting the new direction by TPAC.

**Comment by anssiko** [comment]
Before updating the spec itself, I thought it might be a good idea to investigate how the mediacapture-worker with mediacapture-depth would look like from the web developers' point of view (to take API ergonomics into consideration).

Let's take the following use case and try to implement it in JavaScript:
- Acquire RGB and depth stream from a device camera, do some processing on the depth stream to turn it into grayscale appropriate for visual representation, playback the resulting grayscale representation alongside its RGB video counterpart.

Below is a first stab of some JavaScript that _should_ achieve the above use case. @ChiahungTai please review. Does this behave as expected? Also @huningxin @robman feel free to chime in.

```
<video id="video">
<video id="depth">

<script>

navigator.mediaDevices.getUserMedia({ depth: true, video: true })
  .then(function (mediaStream) {

    var worker = new Worker("worker.js"),
        rgbVideo = document.querySelector('#video'),
        depthVideo = document.querySelector('#depth');

    // make `mediaStream` the media resource for `rgbVideo`
    rgbVideo.srcObject = mediaStream;
    // start playback of the RGB video
    rgbVideo.play();

    // extract `mediaStreamTrack` of kind "depth" from `mediaStream`
    var mediaStreamTrack = mediaStream.getDepthTracks()[0];

    // associate `worker` with `mediaStreamTrack`
    var processedMediaStreamTrack = mediaStreamTrack.addVideoProcessor(worker);

    // construct `processedMediaStream` using `processedMediaStreamTrack`
    var processedMediaStream = new MediaStream([processedMediaStreamTrack]);

    // make `processedMediaStream` the media resource for `depthVideo`
    depthVideo.srcObject = processedMediaStream;
    // start playback of the grayscale representation
    depthVideo.play();

});

</script>


// worker.js

onvideoprocess = function (event) {

  // `inputImageBitmap` is an `ImageBitmap` obtained from `mediaStreamTrack`
  var input = event.inputImageBitmap;
  // convert `input` of type `ImageBitmap` into a grayscale representation
  // `output` of type `ImageBitmap`
  // TODO: implement `depthMapToGrayscale()` to validate feasibility
  var output = depthMapToGrayscale(input);
  // assign `output` to `outputImageBitmap`, causes the `processedMediaStream`
  // on the main thread to reflect the content of `output`
  event.outputImageBitmap = output;

};
```

**Comment by ChiahungTai** [comment]
Looks good to me! Just make sure depthMapToGrayscale(input) will return a new ImageBitmap.

**Comment by anssiko** [comment]
@ChiahungTai Thanks! With this example I wanted to get a feel how a "hello world" style example would look like in comparison to the earlier attempt where all the depth processing is done on the main thread: http://w3c.github.io/mediacapture-depth/#examples

@huningxin Could you look at how a web developer might implement `depthMapToGrayscale(input)` to complete the example, and note any gaps or issues there may be in implementing it in JS?

I'm trying to gauge whether providing corresponding functionality (like `FrameGrabber`) on the main thread makes sense or not in addition to worker-based processing using the primitives provided by mediacapture-worker and its depth integration. If the worker-based processing is relatively simple from the web developers point of view, I believe we do not need to enable processing on the main thread unless we have good use cases for that.

Some things to consider:
- API ergonomics
  - the API should be easy to use and hard to misuse
  - optimally the API should be self-documenting and intuitive
  - optimized for common use cases while enables also more advanced use cases
  - aligned with other Web Platform APIs and primitives (e.g. mediacapture-worker is inspired by the [AudioWorker interface](http://webaudio.github.io/web-audio-api/#the-audioworker-interface) so there's some precedence)
- Implementation feasibility
  - performance consequences of the API design
  - implementation complexity

@huningxin @robman WDYT?

**Comment by ChiahungTai** [comment]
@anssiko,
Just give you some information, the WebGL on worker is almost landed its first version. It will not be shipped right now. But there are some follow-up bugs will deal with it. And also the Chrome team send an email to the implementer in Mozilla TW to know the implementation challenge. In Mozilla GFX team, they also try to enable CanvasRenderingContext2D on worker. According to their assessment, the hard part is font. Other works should be not a big problem once the WebGL on worker is landed. So I believe the movement to worker should be a right direction.

**Comment by anssiko** [comment]
@ChiahungTai Thanks for the information. It sounds like the implementations are getting aligned in terms of new APIs exposed to workers. Given this development and direction, I suggest we expose depth to the worker context only. Us mediacapture-depth editors will start to evolve the spec to that direction soon.

**Comment by anssiko** [comment]
The processing model of mediacapture-worker is being discussed, thus any related changes to mediacapture-depth must sync with https://github.com/w3c/mediacapture-worker/issues/20

**Comment by anssiko** [comment]
I added the following explanation of the relationship with mediacapture-worker to Introduction:

> Depth cameras usually produce 16-bit depth values per pixel. However, neither the canvas drawing surface used to draw and manipulate 2D graphics on the web platform nor the `ImageData` interface used to represent image data support 16 bits per pixel. To address the issue, this specification defines a conversion into a 8-bit grayscale representation of a depth map for consumption by APIs that are limited to 8 bits per pixel.
> 
> The Media Capture Stream with Worker specification [MEDIACAPTURE-WORKER] that complements this specification enables processing of 16-bit depth values per pixel required by more advanced use cases.

Feel free to improve the text as needed. Perhaps we should also mention the performance penalty that is incurred if the video+canvas indirection is used?

https://w3c.github.io/mediacapture-depth/#introduction

**Comment by huningxin** [comment]
@anssiko , thanks for the editing! It looks fine to me.

> Perhaps we should also mention the performance penalty that is incurred if the video+canvas indirection is used?

+1. The redundant &lt;video&gt;, &lt;canvas&gt; and depth-to-grayscale color conversion are exact what   [MEDIACAPTURE-WORKER] will resolve.

**Comment by ChiahungTai** [comment]
Looks good to me.
If we use ImageBitmap instead of ImageData and 2DCanvas, that might be easier for WebGL integration too.

**Comment by anssiko** [comment]
Thanks, I elaborated the intro a bit to note the benefits of not needing to use video+canvas indirection: https://github.com/w3c/mediacapture-depth/commit/a4b316eecbb5762c8f765fe6b3bfaa64a92edbd7

**Comment by anssiko** [comment]
This issue has been addressed by settling on the following split:

The [mediacapture-depth](https://w3c.github.io/mediacapture-depth/) spec defines a conversion into a 8-bit grayscale representation of a depth map for consumption by APIs that are limited to 8 bits per pixel.

The [mediacapture-worker](https://w3c.github.io/mediacapture-worker/) spec defines processing of 16-bit depth values per pixel directly in a worker environment.
