### ISSUE TITLE
Publish a new Working Draft

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#89]
We should publish a new Working Draft. Here are the process steps:

To publish a [revision of a Working draft](http://www.w3.org/2015/Process-20150901/#revised-wd), a Working Group
- [x] must record the group's decision to request publication. Consensus is not required, as this is a procedural step,
- [x] must provide public documentation of substantive changes to the technical report since the previous Working Draft,
- [x] should provide public documentation of significant editorial changes to the technical report since the previous step,
- [x] should report which, if any, of the Working Group's requirements for this document have changed since the previous step,
- [x] should report any changes in dependencies with other groups,

I'm happy to prepare the spec for publication. I suggest we plan to publish Tue 08 December 2015.

**Comment by anssiko** [comment]
[W3C Working Draft 08 December 2015](https://w3c.github.io/mediacapture-depth/releases/WD2.html) snapshot created:
- Pass [Pubrules Checker](https://labs.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fmediacapture-depth%2Freleases%2FWD2.html&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004&processDocument=2015)
- Pass [Link Checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fmediacapture-depth%2Freleases%2FWD2.html&hide_type=all&recursive=on&depth=&check=Check)

**Comment by anssiko** [comment]
The [mail sent to the list](https://lists.w3.org/Archives/Public/public-media-capture/2015Nov/0050.html) serves as the group's decision to request publication. With that, we've ticked all the boxes required by the process for a new Working Draft publication.

**Comment by huningxin** [comment]
All looks great to me. Thanks much, @anssiko !

**Comment by anssiko** [comment]
The new Working Draft has now been published:
http://www.w3.org/TR/2015/WD-mediacapture-depth-20151208/
