### ISSUE TITLE
Review and implement the proposed extensibility guidelines

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-depth#92]
Based on discussion at https://github.com/w3c/mediacapture-main/issues/244 a proposal for extensibility section for the mediacapture-main has now been drafted: https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0009.html

We should review the proposal, apply the guidelines for this spec, and provide feedback to the group to help improve the extensibility section accordingly.

**Comment by anssiko** [comment]
Here's the [Defining a new media type](https://w3c.github.io/mediacapture-main/#defining-a-new-media-type-beyond-the-existing-audio-and-video-types) checklist:

At a minimum, defining a new media type would require
- [x] adding a new `getXXXXTracks()` method for the type to the `MediaStream` interface,
  - https://w3c.github.io/mediacapture-depth/#dom-mediastream-getdepthtracks
- [x] describing what a muted or disabled track of that type will render (see 4.3.1 Life-cycle and Media Flow),
  - e0003d6
- [x] adding the new type as an additional legal value for the `kind` attribute on the `MediaStreamTrack` interface,
  - https://w3c.github.io/mediacapture-depth/#mediastreamtrack-interface
- [x] updating the description of the `readonly` attribute on the `MediaStreamTrack` interface,
  - no patching needed, behaves as defined in mediacapture-main https://w3c.github.io/mediacapture-main/#widl-MediaStreamTrack-_readonly
- [x] adding at least one track source type (`SourceTypeEnum`),
  -  6a3f6cf
- [x] defining any constrainable properties (see 4.3.9 Constrainable Properties) that are applicable to the media type,
  - https://w3c.github.io/mediacapture-depth/#depthmapunit-constrainable-property
- [x] updating how the `HTMLMediaElement` works with a `MediaStream` containing a track of the new media type (see 6. MediaStreams in Media Elements),
  - https://w3c.github.io/mediacapture-depth/#media-provider-object
  - https://w3c.github.io/mediacapture-depth/#the-video-element
- [x] updating `MediaDeviceKind`,
  - ee8f7ae
- [x] updating the `getCapabilities()` and `getUserMedia()` descriptions,
  - no patching needed for `getCapabilities()`, behaves as in https://w3c.github.io/mediacapture-main/#widl-InputDeviceInfo-getCapabilities-MediaTrackCapabilities
  - no patching needed for `getUserMedia()`, behaves as in https://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia
- [x] adding the new type to the `MediaStreamConstraints` dictionary, and
  - https://w3c.github.io/mediacapture-depth/#mediastreamconstraints-dictionary
- [x] describing any new security and/or privacy considerations (see 13. Privacy and Security Considerations) introduced by the new type.
  - b3e0604

Additionally, it should include updating
- [x] the source definition,
  - no changes, references https://w3c.github.io/mediacapture-main/#dfn-source
- [x] the list of media stream consumers,
  - fb77c84
- [x] the description of the `label` attribute on the `MediaStreamTrack` interface,
  - no changes, reuses https://w3c.github.io/mediacapture-main/#widl-MediaStreamTrack-label
- [x] the list of sinks (see 5. The model: sources, sinks, constraints, and settings), and
  - no changes (sink is a non-normative synonym to consumer, already defined in fb77c84)
- [x] the best practice statements referring to video and audio (see 10.7 Implementation Suggestions).
  - no need for special-casing for depth

It might also include
- [x] explaining how the media is expected to be used by potential consumers, and
  - discussed in https://w3c.github.io/mediacapture-depth/#use-cases-and-requirements
- [x] giving examples in `MediaStreamTrackState` of how such a track might become ended.
  - no changes, reuses https://w3c.github.io/mediacapture-main/#idl-def-MediaStreamTrackState.ended
    ([Defining a new constrainable property](https://w3c.github.io/mediacapture-main/#defining-a-new-constrainable-property) was addressed in #97.)

**Comment by huningxin** [comment]
@anssiko , thanks for doing this! Do you see any gaps to close this issue?

**Comment by anssiko** [comment]
PR #98 ticked all the boxes in the checklist, closing this issue.
