### ISSUE TITLE
Clarify constraint selection order from getUserMedia

### ISSUE THREAD

**Issue by bbernhar** [w3c/mediacapture-depth#94]
If the UA requests with the constraints of `{video: true, audio: true, depth: true}`, it's not clear if the selected corresponding video device was decided by a paired default audio device and a separate depth device OR a paired depth device and a separate non-default audio device. 

Per 6.6.1, we should consider enforcing the order of selection with a depth constraint where it takes precedence in deciding a corresponding video device. This would prevent selecting a combined stream with separate group identifiers in implementations.

**Comment by huningxin** [comment]
Thanks for bringing this!

Could you please show a use case to elaborate this idea?

**Comment by bbernhar** [comment]
Multiple cameras. Where an `audio+video` pair is selected from a normal video camera first but depth could come from a separate 3D camera that has its own unselected video device. It makes more sense to give precedence to the video device corresponding to that depth device but the spec doesn't require such behavior and leaves it ambiguous.

**Comment by anssiko** [comment]
@bbernhar Thanks for raising this issue.

Is the concern that implementations might not be able to ensure streams sourced from separate physical devices will be synchronized? For example, say, a built-in normal video camera and a separate add-on 3D camera attached to the same system, or other configuration, that could not be grouped by the underlying implementation.

If I got you right, would you prefer to leave it to the implementation to decide whether to allow the creation of the combined [depth+video stream](https://w3c.github.io/mediacapture-depth/#dfn-depth-video-stream) from two physical sources (e.g. in practice, gray out the incompatible device combos in the device picker dialog)? That sounds like a reasonable thing to clarify in the spec, given that the implementation is in the best position to judge for which combos a good enough synchronization can be achieved. We have some [implementation considerations](https://w3c.github.io/mediacapture-depth/#h-implementation-considerations) in the spec, but we could definitely clarify this.

Feel free to propose some text that would address your concern in the spec.

**Comment by bbernhar** [comment]
@anssiko That is correct. The implementation could require a corresponding video device for media capture and cannot be coordinated or synchronized across sources.

Here's one way it could be worded for the spec:

> If the UA requests a combined `depth+video` stream, both of those devices in the constraint should be satisfied as belonging to the same group or physical device. The decision to select and satisfy which device pair is left up to the implementation.

**Comment by huningxin** [comment]
In latest RSSDK, there is a mode called "R200 Enhanced Mode". See https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/index.html?doc_platcam_camera_r200_enhanced.html. In that mode, application is able to request the color stream from the platform camera (separated source of R200 camera) and the depth stream from R200. The usage of this mode is for better color quality. This mode is supported on calibrated devices. In this case, the depth+video can be synchronized, but from different physical devices.

I am thinking about:
1. `video+depth`, select the color and depth from R200.
2. `video{deviceId: platformCamera}+depth`, select the color from platform camera and depth from R200. If device is not calibrated, it reports constraints unsatisfied error.

WDYT?

**Comment by bbernhar** [comment]
@huningxin LGTM. 

If the `video+depth` device pair belong in separate groups, the UA must explicitly require a constraint to select `video{deviceId: platformCamera}+depth`. Provided the implementation can still satisfy the constraint.

**Comment by anssiko** [comment]
@bbernhar Thanks for the proposal, I submitted #95 with your proposed text and some minor copy edits. 

All, @bbernhar @huningxin - please review and see whether it looks good to be merged :-)
